[
  {
    "package": {
      "name": "git-url-parse",
      "version": "1.2.2",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "dstack-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-02-16T08:08:47Z",
        "published": "2023-05-15T06:30:19Z",
        "schema_version": "1.6.0",
        "id": "GHSA-4xqq-73wg-5mjp",
        "aliases": [
          "CVE-2023-32758"
        ],
        "summary": "git-url-parse Regular Expression Denial of Service",
        "details": "giturlparse (aka git-url-parse) through 1.2.2, as used in Semgrep 1.5.2 through 1.24.1, is vulnerable to ReDoS (Regular Expression Denial of Service) if parsing untrusted URLs. This might be relevant if Semgrep is analyzing an untrusted package (for example, to check whether it accesses any Git repository at an http:// URL), and that package's author placed a ReDoS attack payload in a URL used by the package.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "git-url-parse",
              "purl": "pkg:pypi/git-url-parse"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "last_affected": "1.2.2"
                  }
                ]
              }
            ],
            "versions": [
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "1.1.0",
              "1.2.0",
              "1.2.1",
              "1.2.2"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/05/GHSA-4xqq-73wg-5mjp/GHSA-4xqq-73wg-5mjp.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32758"
          },
          {
            "type": "WEB",
            "url": "https://github.com/returntocorp/semgrep/pull/7611"
          },
          {
            "type": "WEB",
            "url": "https://github.com/returntocorp/semgrep/pull/7943"
          },
          {
            "type": "WEB",
            "url": "https://github.com/returntocorp/semgrep/pull/7955"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/coala/git-url-parse"
          },
          {
            "type": "WEB",
            "url": "https://github.com/coala/git-url-parse/blob/master/giturlparse/parser.py#L53"
          },
          {
            "type": "WEB",
            "url": "https://pypi.org/project/git-url-parse"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-1333"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-05-15T20:51:51Z",
          "nvd_published_at": "2023-05-15T04:15:10Z",
          "severity": "HIGH"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-4xqq-73wg-5mjp"
        ],
        "aliases": [
          "CVE-2023-32758",
          "GHSA-4xqq-73wg-5mjp"
        ],
        "max_severity": "7.5"
      }
    ]
  },
  {
    "package": {
      "name": "idna",
      "version": "3.6",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "dstack-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-04-11T21:56:51Z",
        "published": "2024-04-11T21:32:40Z",
        "schema_version": "1.6.0",
        "id": "GHSA-jjg7-2v4v-x38h",
        "aliases": [
          "CVE-2024-3651"
        ],
        "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
        "details": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "idna",
              "purl": "pkg:pypi/idna"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.7"
                  }
                ]
              }
            ],
            "versions": [
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "0.7",
              "0.8",
              "0.9",
              "1.0",
              "1.1",
              "2.0",
              "2.1",
              "2.10",
              "2.2",
              "2.3",
              "2.4",
              "2.5",
              "2.6",
              "2.7",
              "2.8",
              "2.9",
              "3.0",
              "3.1",
              "3.2",
              "3.3",
              "3.4",
              "3.5",
              "3.6"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-jjg7-2v4v-x38h/GHSA-jjg7-2v4v-x38h.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/kjd/idna"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-400"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-04-11T21:32:40Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-jjg7-2v4v-x38h"
        ],
        "aliases": [
          "CVE-2024-3651",
          "GHSA-jjg7-2v4v-x38h"
        ],
        "max_severity": "6.2"
      }
    ]
  }
]