[
  {
    "package": {
      "name": "gitpython",
      "version": "3.1.31",
      "ecosystem": "PyPI"
    },
    "vulnerabilities": [
      {
        "modified": "2023-08-25T16:19:20Z",
        "published": "2023-08-11T09:30:36Z",
        "schema_version": "1.4.0",
        "id": "GHSA-pr76-5cm5-w9cj",
        "aliases": [
          "CVE-2023-40267"
        ],
        "summary": "GitPython vulnerable to remote code execution due to insufficient sanitization of input arguments",
        "details": "GitPython before 3.1.32 does not block insecure non-multi options in `clone` and `clone_from`, making it vulnerable to Remote Code Execution (RCE) due to improper user input validation, which makes it possible to inject a maliciously crafted remote URL into the clone command. Exploiting this vulnerability is possible because the library makes external calls to git without sufficient sanitization of input arguments. NOTE: this issue exists because of an incomplete fix for CVE-2022-24439.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.32"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-pr76-5cm5-w9cj/GHSA-pr76-5cm5-w9cj.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-40267"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1609"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/commit/ca965ecc81853bca7675261729143f54e5bf4cdd"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-137.yaml"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AV5DV7GBLMOZT7U3Q4TDOJO5R6G3V6GH/"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PF6AXUTC5BO7L2SBJMCVKJSPKWY52I5R/"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-78"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-08-11T19:48:27Z",
          "nvd_published_at": null,
          "severity": "CRITICAL"
        }
      },
      {
        "modified": "2023-08-29T23:51:29Z",
        "published": "2023-08-29T23:33:53Z",
        "schema_version": "1.4.0",
        "id": "GHSA-wfm5-v35h-vwf4",
        "aliases": [
          "CVE-2023-40590"
        ],
        "summary": "GitPython untrusted search path on Windows systems leading to arbitrary code execution",
        "details": "### Summary\n\nWhen resolving a program, Python/Windows look for the current working directory, and after that the PATH environment (see big warning in https://docs.python.org/3/library/subprocess.html#popen-constructor). GitPython defaults to use the `git` command, if a user runs GitPython from a repo has a `git.exe` or `git` executable, that program will be run instead of the one in the user's `PATH`.\n\n### Details\n\nThis is more of a problem on how Python interacts with Windows systems, Linux and any other OS aren't affected by this. But probably people using GitPython usually run it from the CWD of a repo.\n\nThe execution of the `git` command happens in\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/cmd.py#L277 \n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/cmd.py#L983-L996\n\nAnd there are other commands executed that should probably be aware of this problem.\n\n### PoC\n\nOn a Windows system, create a `git.exe` or `git` executable in any directory, and import or run GitPython from that directory\n\n```\npython -c \"import git\"\n```\n\nThe git executable from the current directory will be run.\n\n### Impact\n\nAn attacker can trick a user to download a repository with a malicious `git` executable, if the user runs/imports GitPython from that directory, it allows the attacker to run any arbitrary commands.\n\n### Possible solutions\n \n- Default to an absolute path for the git program on Windows, like `C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE` (default git path installation).\n- Require users to set the `GIT_PYTHON_GIT_EXECUTABLE` environment variable on Windows systems.\n- Make this problem prominent in the documentation and advise users to never run GitPython from an untrusted repo, or set the `GIT_PYTHON_GIT_EXECUTABLE` env var to an absolute path.\n- Resolve the executable manually by only looking into the `PATH` environment variable (suggested by @Byron)\n\n---\n\n> [!NOTE]\n> This vulnerability was reported via email, and it was decided to publish it here and make it public, so the community is aware of it, and a fix can be provided.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "last_affected": "3.1.32"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-wfm5-v35h-vwf4/GHSA-wfm5-v35h-vwf4.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                ""
              ]
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-wfm5-v35h-vwf4"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-40590"
          },
          {
            "type": "WEB",
            "url": "https://docs.python.org/3/library/subprocess.html#popen-constructor"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-426"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-08-29T23:33:53Z",
          "nvd_published_at": null,
          "severity": "HIGH"
        }
      },
      {
        "modified": "2023-08-17T03:22:31Z",
        "published": "2023-08-11T07:15:00Z",
        "schema_version": "1.4.0",
        "id": "PYSEC-2023-137",
        "aliases": [
          "CVE-2023-40267",
          "GHSA-pr76-5cm5-w9cj"
        ],
        "details": "GitPython before 3.1.32 does not block insecure non-multi options in clone and clone_from. NOTE: this issue exists because of an incomplete fix for CVE-2022-24439.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "ca965ecc81853bca7675261729143f54e5bf4cdd"
                  }
                ],
                "repo": "https://github.com/gitpython-developers/GitPython"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.32"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gitpython/PYSEC-2023-137.yaml"
            }
          }
        ],
        "references": [
          {
            "type": "FIX",
            "url": "https://github.com/gitpython-developers/GitPython/commit/ca965ecc81853bca7675261729143f54e5bf4cdd"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1609"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-pr76-5cm5-w9cj",
          "PYSEC-2023-137"
        ]
      },
      {
        "ids": [
          "GHSA-wfm5-v35h-vwf4"
        ]
      }
    ]
  },
  {
    "package": {
      "name": "requests",
      "version": "2.28.2",
      "ecosystem": "PyPI"
    },
    "vulnerabilities": [
      {
        "modified": "2023-06-20T14:40:07Z",
        "published": "2023-05-22T20:36:32Z",
        "schema_version": "1.4.0",
        "id": "GHSA-j8r2-6x86-q33q",
        "aliases": [
          "CVE-2023-32681"
        ],
        "summary": "Unintended leak of Proxy-Authorization header in requests",
        "details": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP \u2192 HTTPS: **leak**\n2. HTTPS \u2192 HTTP: **no leak**\n3. HTTPS \u2192 HTTPS: **leak**\n4. HTTP \u2192 HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "requests",
              "purl": "pkg:pypi/requests"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.3.0"
                  },
                  {
                    "fixed": "2.31.0"
                  }
                ]
              }
            ],
            "versions": [
              "2.10.0",
              "2.11.0",
              "2.11.1",
              "2.12.0",
              "2.12.1",
              "2.12.2",
              "2.12.3",
              "2.12.4",
              "2.12.5",
              "2.13.0",
              "2.14.0",
              "2.14.1",
              "2.14.2",
              "2.15.0",
              "2.15.1",
              "2.16.0",
              "2.16.1",
              "2.16.2",
              "2.16.3",
              "2.16.4",
              "2.16.5",
              "2.17.0",
              "2.17.1",
              "2.17.2",
              "2.17.3",
              "2.18.0",
              "2.18.1",
              "2.18.2",
              "2.18.3",
              "2.18.4",
              "2.19.0",
              "2.19.1",
              "2.20.0",
              "2.20.1",
              "2.21.0",
              "2.22.0",
              "2.23.0",
              "2.24.0",
              "2.25.0",
              "2.25.1",
              "2.26.0",
              "2.27.0",
              "2.27.1",
              "2.28.0",
              "2.28.1",
              "2.28.2",
              "2.29.0",
              "2.3.0",
              "2.30.0",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.4.3",
              "2.5.0",
              "2.5.1",
              "2.5.2",
              "2.5.3",
              "2.6.0",
              "2.6.1",
              "2.6.2",
              "2.7.0",
              "2.8.0",
              "2.8.1",
              "2.9.0",
              "2.9.1",
              "2.9.2"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/05/GHSA-j8r2-6x86-q33q/GHSA-j8r2-6x86-q33q.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                "requests.sessions.SessionRedirectMixin.rebuild_proxies"
              ]
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
          },
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/psf/requests"
          },
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-200"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-05-22T20:36:32Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-06-05T01:13:00Z",
        "published": "2023-05-26T18:15:00Z",
        "schema_version": "1.4.0",
        "id": "PYSEC-2023-74",
        "aliases": [
          "CVE-2023-32681",
          "GHSA-j8r2-6x86-q33q"
        ],
        "details": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.\n\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "requests",
              "purl": "pkg:pypi/requests"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                  }
                ],
                "repo": "https://github.com/psf/requests"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.3.0"
                  },
                  {
                    "fixed": "2.31.0"
                  }
                ]
              }
            ],
            "versions": [
              "2.10.0",
              "2.11.0",
              "2.11.1",
              "2.12.0",
              "2.12.1",
              "2.12.2",
              "2.12.3",
              "2.12.4",
              "2.12.5",
              "2.13.0",
              "2.14.0",
              "2.14.1",
              "2.14.2",
              "2.15.0",
              "2.15.1",
              "2.16.0",
              "2.16.1",
              "2.16.2",
              "2.16.3",
              "2.16.4",
              "2.16.5",
              "2.17.0",
              "2.17.1",
              "2.17.2",
              "2.17.3",
              "2.18.0",
              "2.18.1",
              "2.18.2",
              "2.18.3",
              "2.18.4",
              "2.19.0",
              "2.19.1",
              "2.20.0",
              "2.20.1",
              "2.21.0",
              "2.22.0",
              "2.23.0",
              "2.24.0",
              "2.25.0",
              "2.25.1",
              "2.26.0",
              "2.27.0",
              "2.27.1",
              "2.28.0",
              "2.28.1",
              "2.28.2",
              "2.29.0",
              "2.3.0",
              "2.30.0",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.4.3",
              "2.5.0",
              "2.5.1",
              "2.5.2",
              "2.5.3",
              "2.6.0",
              "2.6.1",
              "2.6.2",
              "2.7.0",
              "2.8.0",
              "2.8.1",
              "2.9.0",
              "2.9.1",
              "2.9.2"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/requests/PYSEC-2023-74.yaml"
            }
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
          },
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
          },
          {
            "type": "FIX",
            "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-j8r2-6x86-q33q",
          "PYSEC-2023-74"
        ]
      }
    ]
  }
]