[
  {
    "package": {
      "name": "configobj",
      "version": "5.0.8",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "twarc-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-02-18T05:29:13Z",
        "published": "2023-04-03T06:30:19Z",
        "schema_version": "1.6.0",
        "id": "GHSA-c33w-24p9-8m24",
        "aliases": [
          "CVE-2023-26112"
        ],
        "summary": "configobj ReDoS exploitable by developer using values in a server-side configuration file",
        "details": "All versions of the package configobj are vulnerable to Regular Expression Denial of Service (ReDoS) via the validate function, using (.+?)\\((.*)\\). **Note:** This is only exploitable in the case of a developer, putting the offending value in a server side configuration file.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "configobj",
              "purl": "pkg:pypi/configobj"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "last_affected": "5.0.8"
                  }
                ]
              }
            ],
            "versions": [
              "4.4.0",
              "4.5.0",
              "4.5.1",
              "4.5.2",
              "4.5.3",
              "4.6.0",
              "4.7.0",
              "4.7.1",
              "4.7.2",
              "5.0.0",
              "5.0.1",
              "5.0.2",
              "5.0.3",
              "5.0.4",
              "5.0.5",
              "5.0.6",
              "5.0.7",
              "5.0.8"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/04/GHSA-c33w-24p9-8m24/GHSA-c33w-24p9-8m24.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-26112"
          },
          {
            "type": "WEB",
            "url": "https://github.com/DiffSK/configobj/issues/232"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/DiffSK/configobj"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6BO4RLMYEJODCNUE3DJIIUUFVTPAG6VN"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NZHY7B33EFY4LESP2NI4APQUPRROTAZK"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYU4IHVLOTYMFPH7KDOJGKZQR4GKWPFK"
          },
          {
            "type": "WEB",
            "url": "https://security.snyk.io/vuln/SNYK-PYTHON-CONFIGOBJ-3252494"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-1333"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-04-04T21:40:45Z",
          "nvd_published_at": "2023-04-03T05:15:00Z",
          "severity": "LOW"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-c33w-24p9-8m24"
        ],
        "aliases": [
          "CVE-2023-26112",
          "GHSA-c33w-24p9-8m24"
        ],
        "max_severity": "3.7"
      }
    ]
  },
  {
    "package": {
      "name": "idna",
      "version": "3.6",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "twarc-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-04-11T21:56:51Z",
        "published": "2024-04-11T21:32:40Z",
        "schema_version": "1.6.0",
        "id": "GHSA-jjg7-2v4v-x38h",
        "aliases": [
          "CVE-2024-3651"
        ],
        "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
        "details": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "idna",
              "purl": "pkg:pypi/idna"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.7"
                  }
                ]
              }
            ],
            "versions": [
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "0.7",
              "0.8",
              "0.9",
              "1.0",
              "1.1",
              "2.0",
              "2.1",
              "2.10",
              "2.2",
              "2.3",
              "2.4",
              "2.5",
              "2.6",
              "2.7",
              "2.8",
              "2.9",
              "3.0",
              "3.1",
              "3.2",
              "3.3",
              "3.4",
              "3.5",
              "3.6"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-jjg7-2v4v-x38h/GHSA-jjg7-2v4v-x38h.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/kjd/idna"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-400"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-04-11T21:32:40Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-jjg7-2v4v-x38h"
        ],
        "aliases": [
          "CVE-2024-3651",
          "GHSA-jjg7-2v4v-x38h"
        ],
        "max_severity": "6.2"
      }
    ]
  }
]